### ISSUE TITLE
Please do not post your solution before the end of the day

### ISSUE THREAD

**Issue by NJdevPro** [fuglede/adventofcode#1]
This allows people to cheat. Please wait until tomorrow before posting your solution to today's puzzle, thank you.

**Comment by fuglede** [comment]
I appreciate the concern and am certainly not a fan of cheating either. For Advent of Code in particular, the "end of the day" doesn't mark a barrier between cheating or not; if you're concerned about the global leaderboards, the only important thing is that we don't post solutions before both top 100s have been completely populated (and indeed that has been the rule for this repository as well).

If someone wants solutions before the day has ended, but after the leaderboards are full, they can always go to [the subreddit](https://www.reddit.com/r/adventofcode/); for example, [this thread](https://www.reddit.com/r/adventofcode/comments/k5qsrk/2020_day_03_solutions/) has a ton of solutions for today's challenge, even though today hasn't ended yet.

**Comment by giuliohome** [comment]
LOL 😂 this is one of the most idiotic issues I've seen. People who are cheating have the solutions before the questions are even published. That's why they can solve them in less than one or two minutes, that is less than the time of just reading the text.

By the way, thanks instead for quickly sharing the solutions! Appreciated! Basically it is the **only thing worth it** in the adventofcode game, i.e. looking at code written by other programmers and compare or learn or study... Or simply enjoy the differences 

Have fun

**Comment by fuglede** [comment]
Please mind your language.

For what it's worth, I doubt anybody has found a way to cheat the system. It is certainly possible to solve the questions faster than a few minutes by skimming the questions to pick up the relevant parts. If you want to see what this looks like in practice, check out e.g. [Jonathan Paulson's YouTube channel](https://www.youtube.com/channel/UCuWLIm0l4sDpEe28t41WITA). For some specific tricks for leaderboarding, see e.g. [mcpower's post](https://gist.github.com/mcpower/87427528b9ba5cac6f0c679370789661), or [betaveros' post](https://blog.vero.site/post/advent-leaderboard).

**Comment by giuliohome** [comment]
Looking at a video doesn't change absolutely nothing.
You don't need to cheat the system to read the solutions before the time. That can absolutely happen outside the system.
Solving the question and shooting a video after having prepared it in advance is trivial.
My language is the simple and clear language of the truth.
Nothing to change.
Goodbye

**Comment by NJdevPro** [comment]
@fuglede I was thinking about most of us who will never enter the leaderboard, there is still a spirit of competition. But since the solutions are posted on reddit anyway, I guess my request doesn't matter anymore. :(

**Comment by fuglede** [comment]
@NJdevPro Right, there's really no good solution for private leaderboards, other than operating under a code of honour, and promising each other not to peek the solutions early.
