### ISSUE TITLE
2015 Day 21 incorrect for alternate input

### ISSUE THREAD

**Issue by pareronia** [fuglede/adventofcode#3]
In the puzzle statement it says 'The first character _at or below_ 0 hit points loses'
You are only testing below 0, which works for your input, but not for the following input:
```
Hit Points: 104
Damage: 8
Armor: 1
```
(Expected results are 78 and 148)

**Comment by fuglede** [comment]
We can't have that.

In several cases, the solution does make some fairly strict assumptions about the input. This is the case for instance for all the ones about manually parsing assembly, but also notoriously for [2019-16](https://github.com/fuglede/adventofcode/blob/master/2019/day16/solutions.py) required making a somewhat arbitrary guess for the input and where the solution would work well for all inputs that were given to people but notably not for general inputs of the given form. Not that that's the case for this one of course.
