### ISSUE TITLE
2015 Day 11

### ISSUE THREAD

**Issue by pareronia** [fuglede/adventofcode#4]
https://github.com/fuglede/adventofcode/blob/725569a6b31fffe4e152c741e52700d4c39a561a/2015/day11/solutions.py#L22C1-L22C1

The [problem statement](https://adventofcode.com/2015/day/11) says 'Passwords may not contain the letters i, o, or l, as these letters can be mistaken for other characters and are therefore confusing.' You are checking for 'i', 'o' and 'u'.
Just being pedantic 😉 It obviously didn't make a difference for your input. (Neither for mine when I tried it)

**Comment by fuglede** [comment]
🤨
